version: "3"
services:
  proxy:
    image: itzg/bungeecord
    ports:
      - 25565:25565
    environment:
      TYPE: velocity
      DEBUG: false
    volumes:
      - ./velocity.toml:/server/velocity.toml
      - ./forwarding.secret:/server/forwarding.secret
    depends_on:
      - lobby
