services:
  lobby:
    image: itzg/minecraft-server
    environment:
      TYPE: paper
      USE_AIKAR_FLAGS: true
      EULA: true
      ONLINE_MODE: false
      MEMORY: 1G
      DIFFICULTY: peaceful
      MODE: adventure
      FORCE_GAMEMODE: true
      PVP: false
      SPAWN_ANIMALS: false
      SPAWN_MONSTERS: false
      SPAWN_NPCS: false
      VIEW_DISTANCE: 2
      SIMULATION_DISTANCE: 2
      LEVEL_TYPE: flat
      GENERATOR_SETTINGS: |
        {
          "layers": [
            {
              "block": "minecraft:barrier",
              "height": 64
            }
          ]
        }
      RCON_CMDS_STARTUP: |-
        gamerule doDaylightCycle false
    volumes:
      - ./world:/data/world
      - ./plugins:/plugins
